### ISSUE TITLE
[feature-request] Configurable lazysizes trigger

### ISSUE THREAD

**Issue by frontedbe** [marionnewlevant/craft-picture#3]
As a best practice I always use a 'js-' prefix for stuff that gets manipulated with js. Is it possible to implement a configurable lazysizes trigger so I can keep using 'js-lazyload' for lazysizing instead of the default 'lazyload' trigger? Thanks!

**Comment by marionnewlevant** [comment]
@mdominguez good idea. Thanks! there in v2.2.2
